// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/todo/service.proto

package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoQuery struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoQuery) Reset()         { *m = TodoQuery{} }
func (m *TodoQuery) String() string { return proto.CompactTextString(m) }
func (*TodoQuery) ProtoMessage()    {}
func (*TodoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ba0ff80db64cfb1a, []int{0}
}
func (m *TodoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoQuery.Unmarshal(m, b)
}
func (m *TodoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoQuery.Marshal(b, m, deterministic)
}
func (dst *TodoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoQuery.Merge(dst, src)
}
func (m *TodoQuery) XXX_Size() int {
	return xxx_messageInfo_TodoQuery.Size(m)
}
func (m *TodoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TodoQuery proto.InternalMessageInfo

func (m *TodoQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TodoResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ba0ff80db64cfb1a, []int{1}
}
func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (dst *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(dst, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type Todo struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Complete             bool     `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ba0ff80db64cfb1a, []int{2}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ba0ff80db64cfb1a, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TodoQuery)(nil), "williamhgough.commando.todo.TodoQuery")
	proto.RegisterType((*TodoResponse)(nil), "williamhgough.commando.todo.TodoResponse")
	proto.RegisterType((*Todo)(nil), "williamhgough.commando.todo.Todo")
	proto.RegisterType((*Empty)(nil), "williamhgough.commando.todo.Empty")
}

func init() { proto.RegisterFile("rpc/todo/service.proto", fileDescriptor_service_ba0ff80db64cfb1a) }

var fileDescriptor_service_ba0ff80db64cfb1a = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0xb4, 0x69, 0xd3, 0xfb, 0xff, 0xc5, 0x60, 0x21, 0x14, 0xa5, 0x4b, 0xc8, 0x80,
	0xc2, 0x92, 0x4a, 0x65, 0x60, 0x06, 0x8a, 0x4a, 0x07, 0x86, 0x46, 0x1d, 0x80, 0x2d, 0x24, 0xa7,
	0xd6, 0xc2, 0xee, 0x59, 0xb1, 0x5b, 0xd4, 0x6f, 0xcc, 0xc7, 0x40, 0x76, 0x29, 0x63, 0x53, 0x36,
	0x3f, 0xf9, 0xdd, 0xfb, 0x3d, 0x9d, 0x0d, 0x17, 0x8d, 0xaa, 0x46, 0x86, 0x6a, 0x1a, 0x69, 0x6c,
	0xb6, 0xbc, 0xc2, 0x5c, 0x35, 0x64, 0x88, 0x0d, 0x3f, 0xb9, 0x10, 0xbc, 0x94, 0xab, 0x25, 0x6d,
	0x96, 0xab, 0xbc, 0x22, 0x29, 0xcb, 0x75, 0x4d, 0xb9, 0xb5, 0xa6, 0x43, 0x18, 0x2c, 0xa8, 0xa6,
	0xf9, 0x06, 0x9b, 0x1d, 0x3b, 0x03, 0x9f, 0xd7, 0x91, 0x97, 0x78, 0x59, 0x50, 0xf8, 0xbc, 0x4e,
	0xa7, 0xf0, 0xdf, 0x5e, 0x16, 0xa8, 0x15, 0xad, 0x35, 0xb2, 0x5b, 0x08, 0xec, 0x90, 0x8e, 0xbc,
	0xa4, 0x93, 0xfd, 0x1b, 0x5f, 0xe6, 0x47, 0x92, 0x73, 0x37, 0xb9, 0xf7, 0xa7, 0x4f, 0xd0, 0xb5,
	0xd2, 0x02, 0x66, 0x93, 0x03, 0x60, 0x36, 0x61, 0xe7, 0x10, 0x18, 0x6e, 0x04, 0x46, 0x7e, 0xe2,
	0x65, 0x83, 0x62, 0x2f, 0x58, 0x0c, 0x61, 0x45, 0x52, 0x09, 0x34, 0x18, 0x75, 0x12, 0x2f, 0x0b,
	0x8b, 0x5f, 0x9d, 0xf6, 0x21, 0x78, 0x94, 0xca, 0xec, 0xc6, 0x5f, 0x3e, 0x84, 0x0f, 0x3f, 0x40,
	0x36, 0x87, 0xf0, 0xb9, 0xfc, 0x40, 0xc7, 0x68, 0x6f, 0x15, 0xa7, 0x47, 0x2d, 0x2e, 0x9f, 0x2d,
	0xa0, 0x3f, 0x45, 0xe3, 0x12, 0xaf, 0x5a, 0x13, 0xdd, 0xfa, 0xe2, 0x76, 0x32, 0x7b, 0x85, 0xf0,
	0x4e, 0x08, 0x7b, 0xd4, 0xec, 0x84, 0x16, 0xf1, 0x75, 0xfb, 0x8a, 0x0f, 0x8f, 0xf3, 0x02, 0x50,
	0xa0, 0xa4, 0x2d, 0xfe, 0xa9, 0xf3, 0x09, 0x25, 0xee, 0x7b, 0x6f, 0x5d, 0xab, 0xde, 0x7b, 0xee,
	0x3f, 0xdd, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xce, 0x93, 0x60, 0xed, 0x69, 0x02, 0x00, 0x00,
}
